"""initial migration

Revision ID: 94be482b9b2e
Revises: 
Create Date: 2022-04-16 13:36:15.970130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94be482b9b2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.add_column('reservations', sa.Column('lol', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'lol')
    op.drop_table('contact')
    # ### end Alembic commands ###
